languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "jmp-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://jean-marc.paulin.co.uk/"
title = "Jean-Marc Paulin - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#6b7fc9"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#6b7fc9"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#6b7fc9"
pages = 2
# Set this param to 'true' to swap the bar positions
swapColumns = false
